### ISSUE TITLE
Losing polling resolution

### ISSUE THREAD

**Issue by stackunderflow** [unifi-poller/unifi-poller#177]
I've noticed that the resolution of some of my (InfluxDB) USW insights graphs drops periodically.  The resolution goes back to normal after I restart the unifi-poller service.  Strangely, I don't see any unifi-poller log data in /var/log/syslog or /var/log/messages. Any guidance on how to get that working would be helpful.

Not sure what else I can share other than a screenshot.  I've circled where the resolution drops (the graph becomes less "jaggy"). It shows the start somewhere before 04:00 and resolves after I restart unifi-poller around 09:00.

I'm running Ubuntu 16.04.6 LTS : Linux 4.4.0-171-generic #200-Ubuntu SMP x86_64

<img width="1597" alt="Screen Shot 2020-01-18 at 11 21 13 AM" src="https://user-images.githubusercontent.com/557830/72666982-1ae91b80-39e5-11ea-9419-b221c5c32bba.png">

**Comment by davidnewhall** [comment]
I'm not real sure what to say here. I think finding where systemd is sending your logs is priority one because there may be a clue in there. I'd be curious if somehow the configured interval is not being respected and it floats over time. Looking at the time stamps in the log should show that. Maybe `cd /var/log ; grep -r unifi-poller .` to see if there's something there. You can also look in the systemd journal (but it's usually limited) with something like `sudo systemctl status unifi-poller` and `journalctl -xfu unifi-poller.service` (not tested, and may need tweaks).

Do you know where other apps logs go? Is syslog configured to send them somewhere other than to files?

Poller copies numbers from the UniFi API and stores them in your time series database; it's a generally "dumb" app that serves as a psuedo-clipboard. The next thing to figure out is slightly more difficult. Is poller putting the _correct_ numbers into your time series database? To figure this out you'll need to dig into the database and compare the numbers being stored with the numbers coming from the controller. If you jump on Discord we can discuss some ways to go about that.

**Comment by stackunderflow** [comment]
I found where the logs were going.  I'm running Security Onion on this box, and it's ingesting all the logs from unifi-poller.  I didn't think it would automatically do that because I didn't set up any filtering rules for it, but I suppose it's just syslog events, so they were ingested.

Now that I have the logs, I'll do some searching around the timestamps where the resolution drops and report back.

Thanks for the tips.  Your guidance made me look in the obvious place I missed.

**Comment by davidnewhall** [comment]
Hello! Have you any updates since we did a little troubleshooting on this?

**Comment by davidnewhall** [comment]
Please let me know if this continues to be a problem! Thank you!
