### ISSUE TITLE
UAP IW HD: Switch statistics missing

### ISSUE THREAD

**Issue by olmo1501** [unifi-poller/unifi-poller#194]
Hi,

I am missing the statistics of my UAP IW HD switchports. 

I think this device should be discovered as an AP as well as a switch. I am pretty sure the statistics are there because in the past I was able to gather the data using "unifi_miner.pl" (https://github.com/zbx-sadman/unifi_miner) and feed them to Zabbix. Sadly I don't have access to all those scripts anymore. 

I would really love to see this with this amazing project too and am willing to provide any help that will be needed (except sending you the AP ;-))

Thanks a lot and kind regards,
Oliver

**Comment by davidnewhall** [comment]
Hello,

I'm not sure why data is missing from that device. Can you elaborate on what data you're expecting but not seeing? Does the poller output any errors? Do you have other WAPs that are displaying correctly?

Your report doesn't contain any questions and it's missing technical details about your configuration and the problem you're experiencing. Please provide more data so I may offer the best possible support.

Thank you!
-david

**Comment by olmo1501** [comment]
Of course I will elaborate on this:

- My environment consists of a USG 3P, 2 UniFi switches, a UAP nano HD and the mentioned UAP IW HD. Controller is running in an LXC container on Proxmox
- My setup is running completely fine, poller does not report any errors and all devices are displaying correctly.
- My question / feature request is about this device: https://inwall-hd.ui.com/ Additionally to the AP it contains a four-/five-port switch. And I would love to see traffic, errors, drops, etc. of these switchports just like a "regular" switch. I am quite sure that this data is accessible via the UniFi-API because in the past I managed to retrieve this data with assistance of the mentioned "unifi_miner.pl". But my programming skills are way to limited to enhance UniFi Poller.

I hope I managed to explain in detail what I'm asking for. Sorry if I haven't been clear yet, English is not my native language.

Kind regards,
Oliver

**Comment by davidnewhall** [comment]
This is perfectly clear. Thank you. I only have a UAP-AC-PRO that has a second port, but I have nothing connected to it. I'm not entirely sure what your device looks like in the API output. Perhaps you can send me the output for this device and I can figure out how to add the port data.

The following command _should_ produce a chunk of JSON from your controller API. This contains all of your `UAP` device data. Can you gzip that data and [email](mailto:david@sleepers.pro) it to me?

```shell
unifi-poller -j d -c up.conf | grep -v INFO | jq '.data[]  | select(.type == "uap")'
```

This requires a config file that has at a minimum unifi url, user and pass. You also need `jq` installed. If you can't install jq, then remove that and send me all of the data. Thank you!

Since you're running in a container, you will need to install this on a Linux host or something. It's pretty easy to install and use (then remove if you choose to). You can possibly run it directly from the container, but I have less experience with that.

**Comment by davidnewhall** [comment]
I just bought a UAP-IW-HD-US - it'll be here in 2 days. It'll be for sale in 3. I'll get this working....

**Comment by olmo1501** [comment]
Good morning,

I just emailed the requested information. Switch port table is included in the output so I'm still hoping that my request will be possible.

Just a short note on the AP pro: this AP has a secondary ethernet port which is bridged to the primary port, it does not include a switch. So it will probably look different from the UAP IW HD in the API output.

By the way: I did not want to make you spend any money on this.

Thank you,
Oliver

**Comment by davidnewhall** [comment]
No worries! I bought it because I wanted to play with it. :) I don't mind losing $20 or so to learn new things and write useful code. I can resell it for only a small loss.

I can probably make this work with the output you provided, but I can actually test it and visualize success if I have the device in a poll-able controller. Give me a week or two to work on this and see if we can make it work. Thank you!

**Comment by davidnewhall** [comment]
I have my new device. Kinda tied up atm, but will get this added soon!

**Comment by davidnewhall** [comment]
I swear I'll work on this soon.. Life has been crazy.

https://twitter.com/TwitchCaptain/status/1231812561391120388

**Comment by olmo1501** [comment]
Take your time, I'll be patient.

**Comment by davidnewhall** [comment]
This actually looks pretty easy. The port table data is already being collected by the API library. I just have to add it to the output libraries so it gets written to the database(s).  It's very similar to the port data on a normal USW, so most of the bases are covered. Hope to have something soon!

**Comment by davidnewhall** [comment]
Testing the changes now. I have a few other things I want to button up before I drop a new release, but should get it handled shortly.

**Comment by davidnewhall** [comment]
This commit https://github.com/unifi-poller/influxunifi/commit/979ea0c9c1a07b741b10df58e5736b655d7352ee adds UAP port table data to InfluxDB (no PR, sadly). This commit https://github.com/unifi-poller/promunifi/commit/2f200a8d7632fdd80e8bd894d81934d8ab96e7f3 adds UAP port table data to Prometheus (also no PR). The next release will contain this data. I just hope to remember to add it to the dashboards. :D
