### ISSUE TITLE
UNRESOLVED: How to show top 10 UAP/clients in a graph

### ISSUE THREAD

**Issue by suporte-seven2020** [unifi-poller/unifi-poller#216]
Hi guys,

I'm setting unifipoller with grafana and I'm very new to this. In the graph bellow you can see the default setting. This dashboard I just got from grafana.com (UniFi-Poller: Client Insights - InfluxDB). However, I would like to filter it to have only the relevant information because there are too many users in the unifi controller. It is about 290 UAPs in the whole network. It is in a hotel.

How can I only show the top 10 UAPs with the majority of clients connected currently? I don't need to have information on UAPs with 1 client connected, for example.

I hope you could help me.

![image](https://user-images.githubusercontent.com/64317948/80282665-2ab18380-86e9-11ea-9b66-d671d5a150fc.png)

Thanks in advance!

**Comment by davidnewhall** [comment]
You can select specific APs in the drop down menu at the top. That's probably not what you want though. It sounds like you're at a point where you're about to learn Grafana. :) Good luck!

**Comment by suporte-seven2020** [comment]
So, it sounds like you won't help me, right? :/

**Comment by davidnewhall** [comment]
That's a really crummy way to ask that question. I spent a lot of time building the software that's putting your controller metrics into a time series database so you can visualize them with Grafana. I'm sorry you are unfamiliar with Grafana, but I do not have time to teach it to you. If what you were asking was simple, I'd give you some ideas, but I don't know how to do what you asked for offhand. The Internet is full of people who may be able to help you; try Discord or Slack.

**Comment by suporte-seven2020** [comment]
I'm sorry David. I thought what I have asked wasn't something difficult to implement or adjust, specially to people who have much more experience on Grafana than me. I've already search A LOT on the internet with no success, for this reason I have asked in the communities.
Sorry for bothering you. 
Thanks. I'll search about Discord or Slack to check if them can help me.

**Comment by suporte-seven2020** [comment]
David, 
Discord and Slack are softwares to chat, like Telegram. How would this help me? Sorry, but I have never used both of them. I've installed Discord and I have even searched for Grafana servers but I could not find anything. Did you really mean it could help me find someone who can help me in this chat software or did you misunderstand what my problem really is?
Thanks again.

**Comment by davidnewhall** [comment]
Honestly, I'm not sure what you're looking for is possible with Grafana. I'm really not sure off hand. You only want to display metrics that are greater than 0 or 1 is what I'm understanding. Since you're new to Grafana, you need someone that can help you learn it or modify the graphs in a way that suit your needs. 

Grafana provides community support in their Slack. You need to make an account, get the app and join the server. I'm not real sure how to do all that offhand, but it's a possibility. Grafana also has forums where you can ask others for help. 

Discord is where I hang out, along with dozens of other UniFi users that use the poller software for insights. The [Ubiquiti discord server](https://discord.gg/ui) has a channel named #uniifi-poller where you can get assistance and ask questions. 

Good luck!

**Comment by calebcall** [comment]
This is more of an influxdb question than a Grafana question.  Here's a SO article that talks about doing what you're looking for I believe @suporte-seven2020 https://stackoverflow.com/questions/41187962/influxdb-select-top-n-results-from-a-group-by-tag

**Comment by PianSom** [comment]
It sounds like the previous answer is about right.

However, in your example you could produce graphs of arbitrary APs by first sorting by AP by clicking on the "current" column header to order the rows then command/control clicking on individual rows (eg the top ten) to select them for inclusion in the graph

PS In case you didn't know, davidnewhall made a discord post on your behalf, asking for help

**Comment by suporte-seven2020** [comment]
Hi @davidnewhall 
Thank you for the help. I'll check for the ubiquiti Discord server.

In regards to what I'm looking for, I think you misunderstood me. I'll to try clear it up. Let's supose I have 50 UAPs in my wireless network. Among them I have 1 UAP with 5 clients connected, 2 UAPs with 10 clients, 2 UAPs with 50 clients, 10 UAPs with 8 clients, and so on. The graph will show all of the 50 UAPs  with all its information, as I have showed in the image. However, I don't want to have all of them in the graph because it is too much information do manage. Imagine 295 UAPs with 1500 clients, which is my scenary. I just want to have the top 10 UAPs. In other words, only the first 10 UAPs, which would be the ones with more clients connected at that moment. I think it is like a filter in the database.

I hope it's more clear now.
Thank you!

**Comment by suporte-seven2020** [comment]
> This is more of an influxdb question than a Grafana question. Here's a SO article that talks about doing what you're looking for I believe @suporte-seven2020 https://stackoverflow.com/questions/41187962/influxdb-select-top-n-results-from-a-group-by-tag

Thanks man! I'll check it out.

**Comment by suporte-seven2020** [comment]
> arbitrary

I know what you mean. It also would work. However, I would prefer something automatic as I have just explained to David in the post above.

I din't know about David's post on my behaf. 
Thanks.

**Comment by davidnewhall** [comment]
My final thoughts on this: It's an InfluxDB "problem" because the solution requires crafting an InfluxDB query (or several) that allow you to get the data you want. 

Here's the problem with this ideal: The original post includes a time series graph. If you want to know what the "top anything are right now" that has nothing to with time series. You cannot graph that. The top 10 now may not be the same top 10 in 5 mines, and it could change every second. If the environment had 100,000 APs to choose from you'd never have the same top 10 at any point in time. 

Now, if the request is I just want a panel (probably a table) with the top 10 right now, you can likely pull that off. Again, I'm not an InfluxDB expert and it would take me quite a bit of time to create this query; just like it'll take anyone else. I can explain it though. Do a SELECT to get all APs and their user count. You ORDER BY user_count DESCENDING and LIMIT to 10. That first select may be tuff to figure out and it may even need to be a sub select as shown in the previously-linked SO article.

---

I'm pretty sure you can look at the included panels to craft one that show you user count per AP. Once you have that, order the legend by count and you can see the top10 pretty quickly.

Hope all this helps!

**Comment by suporte-seven2020** [comment]
Hi David,

 

THank you very much!

Best regards,

 

Sandrigo.

 

De: David Newhall ***@***.*** 
Enviada em: segunda-feira, 8 de março de 2021 00:40
Para: unifi-poller/unifi-poller ***@***.***>
Cc: suporte-seven2020 ***@***.***>; Mention ***@***.***>
Assunto: Re: [unifi-poller/unifi-poller] UNRESOLVED: How to show top 10 UAP/clients in a graph (#216)

 

My final thoughts on this: It's an InfluxDB "problem" because the solution requires crafting an InfluxDB query (or several) that allow you to get the data you want.

Here's the problem with this ideal: The original post includes a time series graph. If you want to know what the "top anything are right now" that has nothing to with time series. You cannot graph that. The top 10 now may not be the same top 10 in 5 mines, and it could change every second. If the environment had 100,000 APs to choose from you'd never have the same top 10 at any point in time.

Now, if the request is I just want a panel (probably a table) with the top 10 right now, you can likely pull that off. Again, I'm not an InfluxDB expert and it would take me quite a bit of time to create this query; just like it'll take anyone else. I can explain it though. Do a SELECT to get all APs and their user count. You ORDER BY user_count DESCENDING and LIMIT to 10. That first select may be tuff to figure out and it may even need to be a sub select as shown in the previously-linked SO article.

  _____  

I'm pretty sure you can look at the included panels to craft one that show you user count per AP. Once you have that, order the legend by count and you can see the top10 pretty quickly.

Hope all this helps!
