### ISSUE TITLE
unifi+unifi-poller: add controller certificate verification ("TOFU" certificate pinning)

### ISSUE THREAD

**Issue by lheckemann** [unifi-poller/unifi-poller#266]
It would be nice to behave like a typical browser+user of the unifi controller might — to save the certificate encountered the first time as valid and check against the known certificate when connecting. This would provide a convenient middle ground between not verifying the certificate at all and verifying it against the globally trusted roots, improving security a little, and would IMHO be a more sensible default than not verifying the certificate at all.

**Comment by davidnewhall** [comment]
I'm not sure I like the idea of "saving files" but I could add an option to import an existing file and verify the certificate from the controller matches. In other words, you'd add the cert to poller after you download it from your controller. Would that suffice?

**Comment by lheckemann** [comment]
That's an option and would be an improvement, but doesn't provide an option which improves security with no additional effort on the part of the user. It is true though that saving the cert somewhere has some further complexity implications, especially if unifi-poller is currently able to run without saving any state at all.

**Comment by davidnewhall** [comment]
> no additional effort on the part of the user

I can provide a `curl` command and decent directions on how to obtain and utilize the cert in Poller. I don't think we're talking about much extra effort to do this. Poller currently does not write files, and if it did, you'd have to setup a place for it to do so (which means there's additional effort going that route too). 

Personally I use a valid cert on my controller, because like you, I'm interested in high transport security. I'd like to see Ubiquiti build in `certbot` and make it automatic at some point. Time will tell.

I'll leave this open to investigate options. Thanks for the feature request!

**Comment by neg2led** [comment]
One thing of note here; when handling self-signed certificates you can just store/verify the certificate's thumbprint (SHA256 hash) rather than the whole cert. Self-signed certs (obviously) have no chain of trust to verify, so all you're really trying to do is make sure it's the same certificate file as it was last time. Shouldn't be particularly difficult to store the fingerprint in a config file.

Though it looks like I'm a little bit late chiming in here! 😝

**Comment by davidnewhall** [comment]
> Though it looks like I'm a little bit late chiming in here

Indeed, I've already added this support. Just working on getting that new feature, and a bunch of others wrapped up. Lots of testing to do....

**Comment by davidnewhall** [comment]
The current release incorporates this feature: https://github.com/unifi-poller/unifi-poller/releases/tag/v2.1.0
Add `ssl_cert_paths` to your unifi controller configuration. ie.
```
[unifi.defaults]
  ssl_cert_paths = ["/etc/unifi-poller/controller.pem", "/config/another.pem"]
```
On Docker you can set `UP_UNIFI_DEFAULTS_SSL_CERT_PATH_0=/config/unifi.pem`.

If any of these files cannot be read the application will refuse to connect to the controller. If the controller certificate is not in one of the files the provided files, the application will refuse to connect.  

To get your PEM file from your controller run this:
```
echo | openssl s_client -showcerts -connect 192.168.3.2:8443
```
Replace the IP with your controller IP and use port 443 is your controller is on port 443. Copy and paste everything between the `BEGIN CERTIFICATE` and `END CERTIFICATE` lines, including those lines as they are. Put that into the controller.pem file and point poller to it.

I hope I remember to put all this in the docs. @PianSom don't let me forget.
